---
- name: Synchronize project with GitHub
  hosts: localhost
  connection: local
  become_user: root

  tasks:
    - name: Add repository to git safe.directory
      ansible.builtin.command: git config --global --add safe.directory "{{ project_path }}"
      changed_when: false
      become: yes 

    - name: Check if path is a git repository
      ansible.builtin.stat:
        path: "{{ project_path }}/.git"
      register: git_dir
      ignore_errors: yes

    - name: Fail if not a git repository
      ansible.builtin.fail:
        msg: "The specified path {{ project_path }} is not a git repository or is not accessible."
      when: not git_dir.stat.exists

    - name: Check for local changes
      ansible.builtin.command: git status --porcelain
      args:
        chdir: "{{ project_path }}"
      register: git_status
      changed_when: false

    - name: "Commit and push changes if there are any"
      block:
        - name: Configure git user name
          ansible.builtin.command: git config --global user.name "Semaphore"
          args:
            chdir: "{{ project_path }}"
          become: yes
        
        - name: Configure git user email
          ansible.builtin.command: git config --global user.email "semaphore@localhost"
          args:
            chdir: "{{ project_path }}"
          become: yes

        - name: Add all changes to staging
          ansible.builtin.command: git add .
          args:
            chdir: "{{ project_path }}"
          become: yes

        - name: Commit changes
          ansible.builtin.command: git commit -m "{{ commit_message }}"
          args:
            chdir: "{{ project_path }}"
          become: yes

        - name: Push changes to remote
          ansible.builtin.command: git push
          args:
            chdir: "{{ project_path }}"
          become: yes
          register: push_result
          
        - name: Show push output
          ansible.builtin.debug:
            var: push_result.stdout_lines

      when: git_status.stdout != ""

    - name: Report no changes
      ansible.builtin.debug:
        msg: "No changes to commit in {{ project_path }}."
      when: git_status.stdout == ""

