- name: Setup Caddy as Reverse Proxy for Grafana
  hosts: localhost
  gather_facts: false
  become: yes
  vars:
    caddy_domain: "notebook.iri1968.dpdns.org"
    grafana_namespace: "monitoring"
    grafana_service: "prometheus-grafana"
    kubeconfig_path: "/home/igor/.kube/config"

  tasks:
    - name: Ensure conflicting services are stopped and disabled
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop:
        - nginx
      ignore_errors: yes

    - name: Install dependencies for Caddy repository
      ansible.builtin.apt:
        name:
          - debian-keyring
          - debian-archive-keyring
          - apt-transport-https
          - curl
        state: present

    - name: Add Caddy GPG key
      ansible.builtin.get_url:
        url: "https://dl.cloudsmith.io/public/caddy/stable/gpg.key"
        dest: "/tmp/caddy.gpg.key"
        mode: '0644'

    - name: De-armor Caddy GPG key
      ansible.builtin.command:
        cmd: gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg /tmp/caddy.gpg.key
        creates: /usr/share/keyrings/caddy-stable-archive-keyring.gpg

    - name: Add Caddy APT repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
        state: present
        filename: caddy-stable

    - name: Install Caddy
      ansible.builtin.apt:
        name: caddy
        update_cache: yes
        state: present

    - name: Check current Grafana service type
      ansible.builtin.shell: "kubectl get svc {{ grafana_service }} -n {{ grafana_namespace }} -o jsonpath='{.spec.type}'"
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: grafana_svc_type_check
      changed_when: false

    - name: Patch Grafana service to NodePort (kubectl)
      ansible.builtin.shell: |
        kubectl patch service {{ grafana_service }} -n {{ grafana_namespace }} \
          --type='merge' -p '{"spec":{"type":"NodePort"}}'
      args:
        executable: /bin/bash
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      changed_when: "'patched' in patch_result.stdout"
      register: patch_result
      when: grafana_svc_type_check.stdout != 'NodePort'

    - name: Get Grafana NodePort
      ansible.builtin.shell: |
        kubectl get svc {{ grafana_service }} -n {{ grafana_namespace }} \
          -o jsonpath='{.spec.ports[0].nodePort}'
      args:
        executable: /bin/bash
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: nodeport_result
      changed_when: false

    - name: Set grafana_nodeport fact
      ansible.builtin.set_fact:
        grafana_nodeport: "{{ nodeport_result.stdout }}"

    - name: "Debug: Show NodePort"
      ansible.builtin.debug:
        msg: "Grafana NodePort is {{ grafana_nodeport }}"

    - name: Configure Caddyfile from template
      ansible.builtin.template:
        src: templates/Caddyfile.j2
        dest: /etc/caddy/Caddyfile
        owner: root
        group: root
        mode: '0644'
      notify: Restart Caddy

  handlers:
    - name: Restart Caddy
      ansible.builtin.systemd:
        name: caddy
        state: restarted
        enabled: yes
        daemon_reload: yes
