- hosts: gw,vds,site
  become: true
  tasks:
    - name: 'Hold grub-pc package on vds3'
      ansible.builtin.dpkg_selections:
        name: grub-pc
        selection: hold
      when: inventory_hostname == 'vds3.iri1968.dpdns.org'

    - name: 'Update apt package cache'
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: 'Upgrade all packages to the latest version'
      ansible.builtin.apt:
        upgrade: 'dist'
        autoremove: true

    - name: 'Check if a reboot is required'
      ansible.builtin.stat:
        path: '/var/run/reboot-required'
      register: 'reboot_required_file'

    - name: 'Reboot the server if required'
      ansible.builtin.reboot:
        msg: 'Reboot initiated by Ansible due to kernel updates'
      when: reboot_required_file.stat.exists
